--- 
title: "GIS Einführung mit QGIS"
author: "Christoph Rinne"
email: crinne@ufg.uni-kiel.de
date: "`r format(Sys.time(), '%d. %B %Y')`"
license: "CC-BY 4.0"
header-includes: 
  \renewcommand{\contentsname}{Inhalt} 
  \renewcommand{\figurename}{Abb.}
  \renewcommand{\tablename}{Tab.}
bibliography: QGIS-cours-references.bib
csl: journal-of-archaeological-science.csl
papersize: a4
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    df_print: kable
urlcolor: blue
link-citations: yes # make citations hyperlinks
linkcolor: blue
number_sections: yes
lang: de-DE
description: 'Gis-Kurs mit QGIS : Tutorial in Kapiteln'
---

# Attribute und Funktionen

Ziel ist die Einführung in die Arbeit mit der Attributtabelle von Vektordaten (Punkt, Linie, Polygon) und den zahlreichen Funktionen. Nicht alle hier gezeigten Schritte liefern ein tolles oder gar wissenschaftlich relevantes Ergebnis. Auch will ich nicht jede Funktion des Menüs und schon gar nicht der Werkzeugkiste durchhecheln. Vielmehr möchte ich mit weitgehend typischen Fragestellungen und möglichen Lösungswegen auf die Arbeit in GIS eingehen.

Daten: Es wird vorrangig mit dem Punktdatensatz der Fundplätze (mallorca-sites.shp) und dem Geländemodell (DGM 200) aus der Karte der vorangehenden Stunde gearbeitet. Beachten Sie, bei textbasierten Datenquellen sind die Editiermöglichkeiten eingeschränkt. 

## Fundplatztypen - Attributtabelle

Öffnen Sie die Attributtabelle zu dem Layer der Fundplätze, z.B. über das Kontextmenü zu diesem Layer. Diese Tabelle kann bzw. wird mit jedem weiteren Aufruf erneut geöffnet (viele Fenster). Natürlich können wir die Spalten sortieren (Mausklick auf die Kopfzeile). 

### Objekte Auswählen

Wir können einzelne oder mehrere Objekte durch Mausklick auswählen und auf diese in der Karte zoomen (\<strg> + \<j> oder das Icon mit der Lupe in der Symbolleiste). Die Reihe gelber Icons bietet weitere Auswahloptionen.   

- "Gelbes Viereck mit 'E'"

Dieses Icon öffnet die filterbasierte Auswahl. Das folgende Fenster, der **Ausdrucksgenerator**, wird noch oft auftauchen und ist äußerst hilfreich. Wir bleiben vorerst auf dem Reiter "Ausdruck". In der linken Spalte können wir Ausdrücke erstellen, wichtige Bausteine wie [=] etc. sehen Sie zur Auswahl direkt darunter. In der mittleren Spalte finden Sie eine Liste diverser optionaler Bestandteile eines Ausdrucks: viele Funktionen, Attribute und Objekteigenschaften. Die Rechte Spalte bietet eine kontextbezogene Hilfe. Ist ihr Ausdruck verständlich (nicht zwingen richtig nach ihrem Verständnis) sehen Sie links unten eine Voransicht.

Klappen Sie in der mittleren Spalte "Felder und Werte" auf, um alle Attribute (Spalten) zu sehen, wählen Sie Tipo_yacim[iento] (Fundplatztyp) 1. mit Doppelklick in den Audruck übernehmen, 2. [Alle eindeutigen]anklicken und 3. in der Liste bis zu "Talaiot" scrollen. Sie sehen zahlreiche Variationen bei denen "Talaiot" stets gleich geschrieben ist. Ergänzen Sie den Ausdruck zu `"Tipo_yacim" like '%Talaiot%'`. Beachten Sie die differenzierte Verwendung von " und ', ebenso das % als sog. *wildcard*. Klicken Sie auf [Objekte wählen], beachten Sie zuvor die optionalen Variationen der *drop-down* Liste des Schalters. Dann [Schließen] Sie das Fenster. 

In der Karte sind zahlreiche Punkte nun gelb markiert, für die Tabelle wählen Sie unten bei [Alle Objekte anzeigen] bitte [**Alle gewählten Objekte anzeigen**]. Eine Alternative schnell die gewählten zu sehen ist das unscheinbare Icon rechts neben dem "Trichter"-Icon, es sortiert alle ausgewählten Datenreihen nach oben.

- "Trichter"-Icon: 

Formular Filter. Der formularbasierte Filter erzeugt zugleich eine Darstellung der Daten in einer Formularansicht. Sie wechseln zwischen Formular- und Tabellenansicht mit den Icons rechts unten in diesem Fenster. In dem formularbasierten Filter kann für jedes Feld ein Eintrag vorgenommen werden und mit einem Schalter am rechten Rand wird die Bedingung (gleich, größer als, enthält etc.) gesetzt.

- Gelbe horizontale Balken: Alle Objekte auswählen
- Gelbes und transparentes Dreieck: Auswahl umkehren
- Gelbes und rotes Viereck: Auswahl löschen (tun Sie dies jetzt bitte) und wählen sie links unten in der Attributtabelle "Alle Objekte anzeigen".

| Annmerkung |
|----|
| [**Talaiot**](https://de.wikipedia.org/wiki/Talayot) (Kat.) oder auch Talayot (ES) sind monumentale Steintürme in eisenzeitlichen Siedlungen und ein wichtiges Element der mallorcinischen Denkmaltopographie. |
| Einführende Literatur:  @guerreroayusoHistoriaIslasBaleares2006c; @guerreroayusoHistoriaIslasBaleares2006b; @lullCeramicaTalayoticaProduccion2008a; @lullTurmbautenSonFornes2007a; @micoperezCronologiaAbsolutaPeriodizacion2005a; @vanstrydonckMyotragusMetellusaJourney2014 |

### Daten verändern

Das Abakus-Icon (Rechenschieber) öffnet den Feldrechner, der in vielen Aspekten dem Ausdrucksgenerator beim Filtern der Daten (s.o.) entspricht. Ziel des nächsten Schrittes ist es, den Höhenwert aus der Rasterzelle des DGM unter jedem Fundpunkt in eine neue Spalte "z_m" zu schreiben. 

Sind Daten ausgewählt, werden a priori nur diese verändert, es sei denn, Sie entfernen die Markierung oben links. Setzen oder belassen Sie bitte folgende Parameter: [x] Neues Feld anlegen, Ausgabefeldname: z_m, Ausgabefeldtyp: Ganzzahl (integer). Bei der Auflösung der Datengrundlage ist eine Dezimalzahl unnötig, damit entfällt auch die Genauigkeit bei den Nachkommastellen. Wählen Sie aus der mittleren Spalte folgende Funktion: Raster -> raster_value. Ergänzen Sie den Namen des DGM-Layers, "1" für das erste ("Farb"-)Band dieses Layers und "\$geometry" (die Punktgeometrie des Fundplatzes) als Referenz. Insgesamt also `raster_value('DGM 200', 1, $geometry)`, [OK]. Für unsere Änderung wurde der Layer in den Editiermodus versetzt (Stift-Icon), die Änderungen müssen noch gespeichert (Diskette-Stift-Icon) und das Editieren (Stift-Icon) beendet werden. Dies können Sie auch in der Icon-Leiste der Karte tun. Beachten Sie dabei bitte die Veränderungen in der Icon-Leiste.

Um einige Möglichkeiten aufzuzeigen und weitere Standardaufgaben durchzuführen, möchte ich folgende Aufgabe zur Übung durchspielen: Wir haben den Verdacht, dass die Lage mindestens eines Punktes auf der Karte (*$geometry*) und der zugehörige Eintrag in der Tabelle (x_utm, y_utm) nicht übereinstimmen. Wir müssen also die x-Koordinaten aller Punkte aus der Geometrie abfragen, auf eine Ganzzahl runden und mit dem Eintrag der Tabelle vergleichen. Ich gehe aus didaktischen Gründen nicht zwingend den kürzesten Weg.   

1. Wir legen ein neues, virtuelles Feld an, benennen es "Test" und definieren es als Text.
2. In der mittleren Spalte unter "Geometry -> \$x" erhalten Sie die x-Koordinaten des Objektes. Ein Umweg wäre also, die Geometrie und hiervon die x-Koordinate abzufragen: ```x($geometry)```. Ein weiterer Umweg wäre die Geometrie als Text abzufragen und die x-Koordinaten herauszuschneiden: ```substr(geomToWKT($geometry),8,6)```. Diese Funktionen können in vielen Kontexten hilfreich sein, ergänzende Erläuterungen erhalten Sie nach der Suche (Lupe!) der jeweiligen Funktion.   
3. Zahlen können gerundet werden `round($x)`, die Erläuterung zu dieser Funktion finden Sie unter "Mathematik".
4. Vergleichen können wir durch Subtraktion, alles was nicht 0 ergibt, ist falsch, oder wir vergleichen wirklich und erhalten "Wahr" oder "Falsch". Die erste Option ist einfach, ergänzen Sie die Syntax einfach zu ```round($x) - "x_utm"```. Die zweite Option ist länger, nutzt aber eine klassische ```if()``` Funktion, die Sie unter Bedingungen finden und die nicht wirklich über die Hilfe hinaus erläutert werden muss: ```if(round($x) = "x_utm", 'identisch', 'verändert')```.

Dies waren einige oft benötigte Standardaufgaben, die Ihnen die Funktionsweise und Möglichkeiten des Feldrechners vor Augen geführt haben sollten. Sie können hier jederzeit auf vorhandene Feldwerte zugreifen, einfache Berechnungen durchführen, Texte verändern und vieles mehr. Sollten Sie die Änderung vorgenommen haben löschen Sie die Spalte "Test" mit 1. Icon "Rote Spalte mit X", 2. Spalte(n) wählen und [OK]. 

### Verknüpfte Daten (Join)

Es kommt oft vor, dass wir eine Geometrie haben und wichtige Daten nur in einer weiteren Text-Tabelle stehen. Wenn es ein gemeinsames Feld gibt, können wir diese Daten verbinden. Die nachfolgend verwendeten Daten stammen aus der Arbeit von Micó (@micoperezCronologiaAbsolutaPeriodizacion2005a). Da eine unabhängige Datenquelle vorliegt, gibt es kein gemeinsames eindeutiges ID-Feld, ich muss stattdessen den Namen des Fundplatzes verwenden. Neben dieser typischen textbasierten Verknüpfung (join) beherrschen GIS auch räumliche Verknüpfungen: identisch, innerhalb, auf und außerhalb (s.u.). 

```
# Quelle: Micó Pérez, R., 2005. Cronología absoluta y periodización 
de la prehistoria [...];c14ID;site;island;monument;context;county;
labcode;bp;std;sample;resource
1;Albufera d'Alcúdia;Mallorca;Sondeo polínico;Z = -19,5m;
Alcúdia/Muro;;32790;;Desconocido;Micó 2005, 24
``` 

Betrachten Sie das vorliegende Datenformat von "sites-c14dat.csv". Die erste Zeile ist ein Kommentar, die zweite Zeile beinhaltet die Spaltennamen, Trennzeichen ist das ";", Dezimaltrennzeichen scheint das "," zu sein, auch wenn es in einem Textfeld steht ("Z = -19,5m"). Fügen Sie die Daten als **getrennten Text** ein (s.o.), achten Sie auf die zu überspringende erste Zeile und wählen Sie "Keine Geometrie". Nur zur Ordnung lege ich im Layerfenster eine Gruppe an (Kontextmenü), benenne diese "Daten", schiebe hier die Tabelle hinein und den gesamten Ordner nach unten.

Öffnen Sie die Eigenschaften zum Layer "Fundplatztypen" und wechseln Sie am linken Fensterrand zu "Verknüpfungen". Fügen Sie mit dem Icon "grünes Plus" eine neue Verknüpfung hinzu, die Parameter sind folgende: Layer verknüpfen: sites-c14dat, Verknüpfungsfeld: site, Zielfeld: Nombre_yac. Optional können Sie unter "Verknüpfte Felder" nicht alle, sondern nur ausgewählte Felder anhängen. Mit "Benutzerfeldnamenpräfix" können Sie statt des Tabellennamens ein kürzeres Präfix für die Spaltennamen angeben. [OK] für diese Verknüpfung und [OK] für das Layout.

Öffnen Sie die Attributtabelle des Layers "Fundplatztypen", filtern Sie (gelbes Viereck + E) auf ` "sites-c14dat_c14ID" > 0` und sortieren Sie diese Daten nach oben. Beachten Sie bitte folgendes: 1. Es gibt nicht viele Gemeinsamkeiten, 2. Sie sehen noch alle Daten der Fundplatztabelle und nur die Daten der 14C-Tabelle, die einen identischen Fundplatznamen haben (*left join*). Für eine genaue Arbeit müssten wir leider noch Energie investieren. Überlegen Sie für sich, was Sie als Datenlieferant besser machen könnten. Löschen Sie diese Verknüpfung bitte wieder, Sie hilft uns nicht wirklich.

# Literatur